networks:
  ran:
    subnet_id: 1
    enable_ipv6: true
  n2:
    subnet_id: 2
    enable_ipv6: false
  n4:
    subnet_id: 3
    enable_ipv6: false
  dataplane:
    subnet_id: 4
    enable_ipv6: true
  sbi:
    subnet_id: 5
    enable_ipv6: false
  db:
    subnet_id: 6
    enable_ipv6: false
  edge0:
    subnet_id: 7
    enable_ipv6: false
  edge1:
    subnet_id: 8
    enable_ipv6: false
  internet:
    subnet_id: 9
    enable_ipv6: false
  n3:
    subnet_id: 10
    enable_ipv6: false




slices:
#  gtp4:
#    n4_upf_id: 2
#    pool: 10.0.100.0/24
#    nssai:
#      sst: 1
#      sd: 0x000001
#    ue: 2

#  non-terrestrial:
#    n4_upf_id: 3
#    pool: 10.0.101.0/24
#    nssai:
#      sst: 1
#      sd: 0x000002
#    ue: 2

  srv6:
    n4_upf_id: 4
    n3_upf_ip: 10.0.200.1
    pool: 10.0.102.0/24
    nssai:
      sst: 1
      sd: 0x000003
    ue: 2

services:
  site1:
    type: nginx
    service_id: 10.0.9.2
    dn:
#      - dnn: internet
#        ipv4: 10.0.9.2
      - dnn: edge0
        ipv4: 10.0.7.2
      - dnn: edge1
        ipv4: 10.0.8.2

  site2:
    type: nginx
    service_id: 10.0.9.3
    dn:
#      - dnn: internet
#        ipv4: 10.0.9.3
      - dnn: edge0
        ipv4: 10.0.7.3
      - dnn: edge1
        ipv4: 10.0.8.3
  site3:
    type: nginx
    service_id: 10.0.9.4
    dn:
#      - dnn: internet
#        ipv4: 10.0.9.4
      - dnn: edge0
        ipv4: 10.0.7.4
      - dnn: edge1
        ipv4: 10.0.8.4
  
  srv6_router:
    type: srv6
    dn:
      - dnn: edge0
        ipv4: 10.0.7.5
      - dnn: edge1
        ipv4: 10.0.8.6
#  dns:
#    type: dns
#    service_id: 10.0.9.1
#    dn:
#      - dnn: internet
#        ipv4: 10.0.9.1
#      - dnn: edge0
#        ipv4: 10.0.7.1
#      - dnn: edge1
#        ipv4: 10.0.8.1

