info:
  version: 1.0.0
  description: AUSF initial local configuration

configuration:
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: ausf.sbi-net # IP used to register to NRF
    bindingIPv4: 10.0.211.5  # IP used to bind the service
    port: 8000 # Port used to bind the service
  serviceNameList: # the SBI services provided by this AUSF, refer to TS 29.509
    - nausf-auth # Nausf_UEAuthentication service
  nrfUri: http://nrf.sbi-net:8000 # a valid URI of NRF
  plmnSupportList: # the PLMNs (Public Land Mobile Network) list supported by this AUSF
    - mcc: 001 # Mobile Country Code (3 digits string, digit: 0~9)
      mnc: 01  # Mobile Network Code (2 or 3 digits string, digit: 0~9)
  groupId: ausfGroup001 # ID for the group of the AUSF

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  AUSF:
    debugLevel: info
    ReportCaller: true
  PathUtil:
    debugLevel: info
    ReportCaller: true
  OpenApi:
    debugLevel: info
    ReportCaller: true
