info:
  version: 1.0.0
  description: UPF configuration
configuration:
  debugLevel: info
  ReportCaller: false
  pfcp:
    - addr: 10.0.210.4
  gtpu:
    - addr: 0.0.0.0
  dnn_list:
    - dnn: sliceA
      cidr: 10.0.222.0/24

