info:
  version: 1.0.0
  description: UPF configuration
configuration:
  debugLevel: info
  ReportCaller: false
  pfcp:
    - addr: 10.0.213.3
  gtpu:
    #- addr: fd00:d0cc:e700:1111:4::3
    - addr: 10.0.201.3
    - addr: 10.0.215.2
  dnn_list:
    - dnn: sliceA
      cidr: 10.0.222.0/24

