iproute2:
  rttable-number: 100
  rtproto-number: 100
  post-init-hook: "post-init-hook.sh"
  pre-init-hook: "pre-init-hook.sh"
locator: "fd00:51D5:0000:1::/64"
endpoints:
  - sid: "fd00:51D5:0000:1:1::/80"
    behavior: "End"
  - sid: "fd00:51D5:0000:1:69::/80"
    behavior: "End.M.GTP6.E"
    options:
      set-source-address: "fd00:51D5:0000:1:71::/128"
  - sid: "fd00:51D5:0000:1:71::/128"
    behavior: "End.M.GTP6.D"
    options:
      set-source-address: "fd00:51D5:0000:1:69::/128"
policy:
  segments-list:
    - "fd00:51D5:0000:2:1::"
    - "fd00:51D5:0000:2:11::"
