iproute2:
  rttable-number: 100
  rtproto-number: 100
  post-init-hook: "post-init-hook.sh"
  pre-init-hook: "pre-init-hook.sh"
locator: "fd00:51D5:0000:2::/64"
endpoints:
  - sid: "fd00:51D5:0000:2:11::/80"
    behavior: "End.DX4"
  - sid: "fd00:51D5:0000:2:1::/80"
    behavior: "End"

