info:
  version: 1.0.2
  description: SMF initial local configuration

configuration:
  smfName: SMF1
  sbi:
    scheme: http
    registerIPv4: smf1.sbi-net # IP used to register to NRF
    bindingIPv4: 10.0.211.3  # IP used to bind the service
    port: 8000
    tls:
      key: config/TLS/smf.key
      pem: config/TLS/smf.pem
  serviceNameList:
    - nsmf-pdusession
    - nsmf-event-exposure
    - nsmf-oam
  snssaiInfos:
    - sNssai:
        sst: 1
        sd: 010203
      dnnInfos:
        - dnn: sliceA
          dns: 
            ipv4: 10.0.224.3
            ipv6: 2001:4860:4860::8888
  plmnList:
    - mcc: "001"
      mnc: "01"

  pfcp:
    addr: 10.0.204.2
  userplaneInformation:
    upNodes:
      ran1:
        type: AN
      upf1:
        type: UPF
        nodeID: 10.0.204.3
        sNssaiUpfInfos:
          - sNssai:
              sst: 1
              sd: 010203
            dnnUpfInfoList:
              - dnn: sliceA
                pools:
                  - cidr: 10.0.222.0/24
        interfaces:
          - interfaceType: N3
            endpoints:
              #- fd00:d0cc:e700:1111:3::2
              - 10.0.203.2
            networkInstance: sliceA
    links:
      - A: ran1
        B: upf1

  nrfUri: http://nrf.sbi-net:8000 
    #  locality: loc1
  ulcl: false

logger:
  SMF:
    debugLevel: trace
    ReportCaller: false
  NAS:
    debugLevel: info
    ReportCaller: false
  NGAP:
    debugLevel: info
    ReportCaller: false
  Aper:
    debugLevel: info
    ReportCaller: false
  PFCP:
    debugLevel: trace
    ReportCaller: false
