# set the network device for satellite terminal and gateway.
nic:
  st: "10.0.216.3"
  gw: "10.0.215.3"

# configure the forward and return links available bandwidth in Mbits/s
bandwidth:
  forward: 10000
  return: 2500

# configure the delay according to the GEO, MEO or LEO satellite and the offset, real delay = delay + or - offset
delay:
  value: 45
  offset: 5 

# set the ACM simulation values
acm:
  - weight: 1
    duration: 10
  - weight: 0.8
    duration: 10
  - weight: 0.9
    duration: 10
  - weight: 0.5
    duration: 10
  - weight: 0.7
    duration: 10
