info:
  version: 1.0.1
  description: Routing information for UE

ueRoutingInfo: # the list of UE routing information
  UE1:
    members:
      - imsi-0010100000000
      - imsi-0010100000001
      - imsi-0010100000002
      - imsi-0010100000003
    topology:
      - A: gnb1
        B: upf1
    specificPath:

