info:
  version: 1.0.1
  description: Routing information for UE

ueRoutingInfo: # the list of UE routing information
  RAN:
    members:
      - imsi-001010000000000
      - imsi-001010000000001
      - imsi-001010000000002
      - imsi-001010000000003

    topology:
      - A: gNB
        B: upf-mec
      - A: upf-mec
        B: upf
    specificPath:
      - dest: 10.0.222.4/30
        path: [upf-mec, upf-mec]
