info:
  version: 1.0.1
  description: Routing information for UE

ueRoutingInfo: # the list of UE routing information

  MEH:
    members:
      - imsi-001010000000001
      - imsi-001010000000002

    topology:
      - A: ran-area1-1
        B: upf-mec-area1
      - A: upf-mec-area1
        B: upf-sliceA
    specificPath:
      - dest: 10.0.224.3/32 # ns1.test
        path: [upf-mec-area1]
      - dest: 10.0.224.6/32 # site2.test
        path: [upf-mec-area1]
      - dest: 10.0.222.0/24 # UE-to-UE
        path: [upf-mec-area1]
      - dest: 10.0.223.0/24 # mec.test
        path: [upf-mec-area1]

  NO-MEH:
    members:
      - imsi-001010000000003
      - imsi-001010000000004
    topology:
      - A: ran-area1-2
        B: upf-mec-area2
      - A: upf-mec-area2
        B: upf-sliceB
    specificPath:

