info:
  version: 1.0.1
  description: UDR initial local configuration

configuration:
  sbi: # Service-based interface information
    scheme: http # the protocol for sbi (http or https)
    registerIPv4: %REGISTER_IP # IP used to register to NRF
    bindingIPv4: %BINDING_IP  # IP used to bind the service
    port: %BINDING_PORT # port used to bind the service
    tls:
      pem: config/TLS/udr.pem
      key: config/TLS/udr.key
  mongodb:
    name: %MONGO_NAME # Database name in MongoDB
    url: mongodb://%MONGO_HOST:%MONGO_PORT # URL of MongoDB
  nrfUri: http://%NRF # a valid URI of NRF

# the kind of log output
  # debugLevel: how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  # ReportCaller: enable the caller report or not, value: true or false
logger:
  UDR:
    debugLevel: trace
    ReportCaller: false
